/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AdminIndexRouteImport } from "./routes/admin/index";
import { Route as AdminMainContentWorksRouteImport } from "./routes/admin/main-content/works";
import { Route as AdminBaseProfileRouteImport } from "./routes/admin/base/profile";
import { Route as AdminBaseNewsletterSubsRouteImport } from "./routes/admin/base/newsletter-subs";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/admin/",
  path: "/admin/",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminMainContentWorksRoute = AdminMainContentWorksRouteImport.update({
  id: "/admin/main-content/works",
  path: "/admin/main-content/works",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminBaseProfileRoute = AdminBaseProfileRouteImport.update({
  id: "/admin/base/profile",
  path: "/admin/base/profile",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminBaseNewsletterSubsRoute = AdminBaseNewsletterSubsRouteImport.update({
  id: "/admin/base/newsletter-subs",
  path: "/admin/base/newsletter-subs",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/admin": typeof AdminIndexRoute;
  "/admin/base/newsletter-subs": typeof AdminBaseNewsletterSubsRoute;
  "/admin/base/profile": typeof AdminBaseProfileRoute;
  "/admin/main-content/works": typeof AdminMainContentWorksRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/admin": typeof AdminIndexRoute;
  "/admin/base/newsletter-subs": typeof AdminBaseNewsletterSubsRoute;
  "/admin/base/profile": typeof AdminBaseProfileRoute;
  "/admin/main-content/works": typeof AdminMainContentWorksRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/admin/": typeof AdminIndexRoute;
  "/admin/base/newsletter-subs": typeof AdminBaseNewsletterSubsRoute;
  "/admin/base/profile": typeof AdminBaseProfileRoute;
  "/admin/main-content/works": typeof AdminMainContentWorksRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/admin"
    | "/admin/base/newsletter-subs"
    | "/admin/base/profile"
    | "/admin/main-content/works";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/admin"
    | "/admin/base/newsletter-subs"
    | "/admin/base/profile"
    | "/admin/main-content/works";
  id:
    | "__root__"
    | "/"
    | "/admin/"
    | "/admin/base/newsletter-subs"
    | "/admin/base/profile"
    | "/admin/main-content/works";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
  AdminBaseNewsletterSubsRoute: typeof AdminBaseNewsletterSubsRoute;
  AdminBaseProfileRoute: typeof AdminBaseProfileRoute;
  AdminMainContentWorksRoute: typeof AdminMainContentWorksRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/": {
      id: "/admin/";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/main-content/works": {
      id: "/admin/main-content/works";
      path: "/admin/main-content/works";
      fullPath: "/admin/main-content/works";
      preLoaderRoute: typeof AdminMainContentWorksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/base/profile": {
      id: "/admin/base/profile";
      path: "/admin/base/profile";
      fullPath: "/admin/base/profile";
      preLoaderRoute: typeof AdminBaseProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/base/newsletter-subs": {
      id: "/admin/base/newsletter-subs";
      path: "/admin/base/newsletter-subs";
      fullPath: "/admin/base/newsletter-subs";
      preLoaderRoute: typeof AdminBaseNewsletterSubsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBaseNewsletterSubsRoute: AdminBaseNewsletterSubsRoute,
  AdminBaseProfileRoute: AdminBaseProfileRoute,
  AdminMainContentWorksRoute: AdminMainContentWorksRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
