/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AdminIndexRouteImport } from "./routes/admin/index";
import { Route as AdminProfileRouteImport } from "./routes/admin/profile";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/admin/",
  path: "/admin/",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: "/admin/profile",
  path: "/admin/profile",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/admin/profile": typeof AdminProfileRoute;
  "/admin": typeof AdminIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/admin/profile": typeof AdminProfileRoute;
  "/admin": typeof AdminIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/admin/profile": typeof AdminProfileRoute;
  "/admin/": typeof AdminIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/admin/profile" | "/admin";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/admin/profile" | "/admin";
  id: "__root__" | "/" | "/admin/profile" | "/admin/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminProfileRoute: typeof AdminProfileRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/": {
      id: "/admin/";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/profile": {
      id: "/admin/profile";
      path: "/admin/profile";
      fullPath: "/admin/profile";
      preLoaderRoute: typeof AdminProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
