#!/usr/bin/env sh
echo "🏗️👷🏽  Styling, testing and building your project before committing"

# Check Prettier Standards
bun run format:check || (
    echo "🧹 Code not formatted. Running Prettier automatically..."
    bun run format
    git add .
)

# Check ESLint Standards
bun run lint ||
(
    echo "😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤
    ESLint Check failed. Make the required changes listed above, add changes and try to commit again."
    false
)

# Check tsconfig Standards
bun run type-check ||
(
    echo "❌😂 Failed Type Check 😂❌
    You can't be serious trying to commit that with the types wrong? Make the changes required above"
    false
)

# If all pass.. try to run a build
bun run build ||
(
    echo "❌👷🏽🔨❌ Better call Bob... Because your build failed ❌👷🏽🔨❌
    Build failed. Fix the issues and try committing again."
    false
)

echo "✅⚔️ Congratulations warrior... Your commit has passed. ⚔️✅"
